package Laundry;

public class HomePage2 extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public HomePage2() {
        initComponents();
        this.setLocationRelativeTo(null);
        label_wellcome.setText("Selamat Datang, "+String.valueOf(adm.nameAdm));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAdmin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button_laporan = new javax.swing.JButton();
        button_order_masuk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        label_wellcome = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuData = new javax.swing.JMenu();
        jMenuItem_Pelanggan = new javax.swing.JMenuItem();
        jMenuItem_Admin = new javax.swing.JMenuItem();
        jMenuTransaksi = new javax.swing.JMenu();
        jMenuItem_CucianMasuk = new javax.swing.JMenuItem();
        jMenuItem_Laporan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("Laundry Management System");
        jLabel1.setToolTipText("");

        button_laporan.setBackground(new java.awt.Color(0, 102, 102));
        button_laporan.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        button_laporan.setForeground(new java.awt.Color(255, 255, 255));
        button_laporan.setText("Laporan Transaksi");
        button_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_laporanActionPerformed(evt);
            }
        });

        button_order_masuk.setBackground(new java.awt.Color(0, 102, 102));
        button_order_masuk.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        button_order_masuk.setForeground(new java.awt.Color(255, 255, 255));
        button_order_masuk.setText("Order Masuk");
        button_order_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_order_masukActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/homepage1.png"))); // NOI18N

        label_wellcome.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        label_wellcome.setText("Selamat Datang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_wellcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_order_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(369, 369, 369))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(button_order_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(button_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label_wellcome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        jMenuData.setText("Data");
        jMenuData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDataActionPerformed(evt);
            }
        });

        jMenuItem_Pelanggan.setText("Pelanggan");
        jMenuItem_Pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PelangganActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItem_Pelanggan);

        jMenuItem_Admin.setText("Admin");
        jMenuItem_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AdminActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItem_Admin);

        jMenuBar1.add(jMenuData);

        jMenuTransaksi.setText("Transaksi");

        jMenuItem_CucianMasuk.setText("Transaksi Cucian");
        jMenuItem_CucianMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CucianMasukActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItem_CucianMasuk);

        jMenuItem_Laporan.setText("Laporan Transaksi");
        jMenuItem_Laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LaporanActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItem_Laporan);

        jMenuBar1.add(jMenuTransaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAdmin))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuDataActionPerformed

    private void jMenuItem_PelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PelangganActionPerformed
        // TODO add your handling code here:
        new Pelanggan().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem_PelangganActionPerformed

    private void jMenuItem_CucianMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CucianMasukActionPerformed
        // TODO add your handling code here:
        new CucianMasuk().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem_CucianMasukActionPerformed

    private void jMenuItem_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AdminActionPerformed
        // TODO add your handling code here:
        new Admin().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem_AdminActionPerformed

    private void jMenuItem_LaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LaporanActionPerformed
        // TODO add your handling code here:
        new LaporanTransaksi().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem_LaporanActionPerformed

    private void button_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_laporanActionPerformed
        new LaporanTransaksi().show();
        this.dispose();
    }//GEN-LAST:event_button_laporanActionPerformed

    private void button_order_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_order_masukActionPerformed
        new CucianMasuk().show();
        this.dispose();
    }//GEN-LAST:event_button_order_masukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_laporan;
    private javax.swing.JButton button_order_masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuData;
    private javax.swing.JMenuItem jMenuItem_Admin;
    private javax.swing.JMenuItem jMenuItem_CucianMasuk;
    private javax.swing.JMenuItem jMenuItem_Laporan;
    private javax.swing.JMenuItem jMenuItem_Pelanggan;
    private javax.swing.JMenu jMenuTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAdmin;
    private javax.swing.JLabel label_wellcome;
    // End of variables declaration//GEN-END:variables
}
